"""add crm integration

Revision ID: 1b8777b25fbb
Revises: e45101b72f2d
Create Date: 2026-05-25 21:11:54.432122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b8777b25fbb'
down_revision: Union[str, None] = 'e45101b72f2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('crm_type', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('subdomain', sa.String(length=255), nullable=True),
    sa.Column('api_token', sa.Text(), nullable=True),
    sa.Column('custom_mappings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_crm_configs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crm_configs')),
    sa.UniqueConstraint('tenant_id', 'crm_type', name='uq_crm_configs_tenant_id_crm_type')
    )
    op.add_column('tender_matches', sa.Column('crm_deal_id', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tender_matches', 'crm_deal_id')
    op.drop_table('crm_configs')
    # ### end Alembic commands ###
