"""add_presets_to_profiles

Revision ID: 1eea935554fc
Revises: b1a2c3d4e5f6
Create Date: 2026-05-24 16:58:23.071153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eea935554fc'
down_revision: Union[str, None] = 'b1a2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_profiles', sa.Column('preset_code', sa.String(length=64), nullable=True))
    op.add_column('search_profiles', sa.Column('niche_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###

    # Backfill existing profiles with HVAC preset values
    hvac_desc = (
        "Мы занимаемся ТОЛЬКО системами отопления, вентиляции и кондиционирования воздуха (HVAC) "
        "для зданий, помещений, офисов, промышленных объектов (поставка, монтаж, обслуживание, ремонт "
        "бытовых, полупромышленных и промышленных сплит-систем, мульти-сплит, VRF/VRV систем, "
        "приточно-вытяжной вентиляции и т.д.).\n\n"
        "КАТЕГОРИЧЕСКИ НЕПОДХОДЯЩИЕ тендеры:\n"
        "1. Кондиционирование транспорта: кондиционеры для тракторов, комбайнов, автобусов, поездов, "
        "вагонов метро, легковых и грузовых автомобилей, спецтехники.\n"
        "2. Охлаждение шкафов автоматики, телекоммуникационных или серверных стоек (если это не "
        "кондиционирование самого помещения серверной).\n"
        "3. Тендеры, не связанные с климатическим оборудованием (бытовая техника, общестроительные работы "
        "без вентиляции/кондиционирования)."
    )

    op.execute(
        sa.text(
            "UPDATE search_profiles "
            "SET preset_code = 'hvac', niche_description = :niche_desc"
        ).bindparams(niche_desc=hvac_desc)
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_profiles', 'niche_description')
    op.drop_column('search_profiles', 'preset_code')
    # ### end Alembic commands ###
