"""add_billing_and_subscriptions

Revision ID: 3c1d3f2401c8
Revises: f4b58455cdfd
Create Date: 2026-05-28 00:10:22.681347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c1d3f2401c8'
down_revision: Union[str, None] = 'f4b58455cdfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('plan', sa.String(length=64), server_default='free', nullable=False))
    op.add_column('tenants', sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tenants', sa.Column('ai_credits_used', sa.Integer(), server_default='0', nullable=False))
    op.add_column('tenants', sa.Column('billing_cycle_started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'billing_cycle_started_at')
    op.drop_column('tenants', 'ai_credits_used')
    op.drop_column('tenants', 'subscription_expires_at')
    op.drop_column('tenants', 'plan')
    # ### end Alembic commands ###
