"""add_tender_match_ai_fields

Revision ID: 6ee65bf29f66
Revises: e54f44ad657e
Create Date: 2026-05-23 18:51:31.830814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ee65bf29f66'
down_revision: Union[str, None] = 'e54f44ad657e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tender_matches', sa.Column('ai_relevance', sa.Boolean(), nullable=True))
    op.add_column('tender_matches', sa.Column('ai_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tender_matches', 'ai_analysis')
    op.drop_column('tender_matches', 'ai_relevance')
    # ### end Alembic commands ###
