"""add search profile schedule fields

Revision ID: dc62d3e5004d
Revises: 6ee65bf29f66
Create Date: 2026-05-23 18:18:31.119008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc62d3e5004d'
down_revision: Union[str, None] = '6ee65bf29f66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_profiles', sa.Column('schedule_interval', sa.String(length=64), nullable=True))
    op.add_column('search_profiles', sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_profiles', 'last_run_at')
    op.drop_column('search_profiles', 'schedule_interval')
    # ### end Alembic commands ###
