"""add_is_matched_checked

Revision ID: e45101b72f2d
Revises: 13a0a9ae26d7
Create Date: 2026-05-25 23:24:42.793795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e45101b72f2d'
down_revision: Union[str, None] = '13a0a9ae26d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenders', sa.Column('is_matched_checked', sa.Boolean(), nullable=True))
    op.execute("UPDATE tenders SET is_matched_checked = FALSE")
    op.alter_column('tenders', 'is_matched_checked', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenders', 'is_matched_checked')
    # ### end Alembic commands ###
