"""add_search_profile_fields

Revision ID: e54f44ad657e
Revises: 20260504_0001
Create Date: 2026-05-23 15:07:33.735195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e54f44ad657e'
down_revision: Union[str, None] = '20260504_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_profiles', sa.Column('regions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('search_profiles', sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('search_profiles', sa.Column('min_score', sa.Numeric(precision=5, scale=2), nullable=True))
    
    # Populate existing rows with default values
    op.execute("UPDATE search_profiles SET regions = '[]', categories = '[]', min_score = 0.0")
    
    # Set to NOT NULL
    op.alter_column('search_profiles', 'regions', nullable=False)
    op.alter_column('search_profiles', 'categories', nullable=False)
    op.alter_column('search_profiles', 'min_score', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_profiles', 'min_score')
    op.drop_column('search_profiles', 'categories')
    op.drop_column('search_profiles', 'regions')
    # ### end Alembic commands ###
